apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-target
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: v1
data:
  workload.fio: '

    [simple-write]

    readwrite=write

    buffered=1

    blocksize=4k

    ioengine=libaio

    directory=/mnt/target

    size=4G

    '
kind: ConfigMap
metadata:
  name: fio-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio
spec:
  backoffLimit: 1
  template:
    metadata:
      name: fio
    spec:
      containers:
      - command:
        - /usr/bin/fio
        - --output-format=json
        - /etc/fio/workload.fio
        image: quay.io/mbukatov/mbukatov-fedora-fio:latest
        name: fio
        volumeMounts:
        - mountPath: /mnt/target
          name: fio-target
        - mountPath: /etc/fio
          name: fio-config-volume
      restartPolicy: Never
      volumes:
      - name: fio-target
        persistentVolumeClaim:
          claimName: fio-target
      - configMap:
          name: fio-config
        name: fio-config-volume
